### ISSUE TITLE
Can you share the training log on CIFAR100 with CE+SR setting?

### ISSUE THREAD

**Issue by chenshen03** [hitcszx/lnl_sr#1]
Thank you for you work!
Can you share the training log on CIFAR100 with CE+SR setting?

**Comment by hitcszx** [comment]
Thanks for your question. Since we are in the submission of neurips, we have pushed the code in a hurry without particular scrutiny, which may lead to some questions and bother you.
The logs ( 0.6 symmetric noise and 0.3 asymmetric noise) for CIFAR-100 are shown as follows:


The log of 0.6 symmetric noise:

> We are using cuda
Namespace(batch_size=128, dataset='CIFAR100', gpus='0', grad_bound=5.0, noise_rate=0.6, noise_type='symmetric', num_workers=10, root='../database/', seed=123)
Files already downloaded and verified
30000 Noisy samples
Class 0, number of noisy 300
Class 1, number of noisy 300
Class 2, number of noisy 300
Class 3, number of noisy 300
Class 4, number of noisy 300
Class 5, number of noisy 300
Class 6, number of noisy 300
Class 7, number of noisy 300
Class 8, number of noisy 300
Class 9, number of noisy 300
Class 10, number of noisy 300
Class 11, number of noisy 300
Class 12, number of noisy 300
Class 13, number of noisy 300
Class 14, number of noisy 300
Class 15, number of noisy 300
Class 16, number of noisy 300
Class 17, number of noisy 300
Class 18, number of noisy 300
Class 19, number of noisy 300
Class 20, number of noisy 300
Class 21, number of noisy 300
Class 22, number of noisy 300
Class 23, number of noisy 300
Class 24, number of noisy 300
Class 25, number of noisy 300
Class 26, number of noisy 300
Class 27, number of noisy 300
Class 28, number of noisy 300
Class 29, number of noisy 300
Class 30, number of noisy 300
Class 31, number of noisy 300
Class 32, number of noisy 300
Class 33, number of noisy 300
Class 34, number of noisy 300
Class 35, number of noisy 300
Class 36, number of noisy 300
Class 37, number of noisy 300
Class 38, number of noisy 300
Class 39, number of noisy 300
Class 40, number of noisy 300
Class 41, number of noisy 300
Class 42, number of noisy 300
Class 43, number of noisy 300
Class 44, number of noisy 300
Class 45, number of noisy 300
Class 46, number of noisy 300
Class 47, number of noisy 300
Class 48, number of noisy 300
Class 49, number of noisy 300
Class 50, number of noisy 300
Class 51, number of noisy 300
Class 52, number of noisy 300
Class 53, number of noisy 300
Class 54, number of noisy 300
Class 55, number of noisy 300
Class 56, number of noisy 300
Class 57, number of noisy 300
Class 58, number of noisy 300
Class 59, number of noisy 300
Class 60, number of noisy 300
Class 61, number of noisy 300
Class 62, number of noisy 300
Class 63, number of noisy 300
Class 64, number of noisy 300
Class 65, number of noisy 300
Class 66, number of noisy 300
Class 67, number of noisy 300
Class 68, number of noisy 300
Class 69, number of noisy 300
Class 70, number of noisy 300
Class 71, number of noisy 300
Class 72, number of noisy 300
Class 73, number of noisy 300
Class 74, number of noisy 300
Class 75, number of noisy 300
Class 76, number of noisy 300
Class 77, number of noisy 300
Class 78, number of noisy 300
Class 79, number of noisy 300
Class 80, number of noisy 300
Class 81, number of noisy 300
Class 82, number of noisy 300
Class 83, number of noisy 300
Class 84, number of noisy 300
Class 85, number of noisy 300
Class 86, number of noisy 300
Class 87, number of noisy 300
Class 88, number of noisy 300
Class 89, number of noisy 300
Class 90, number of noisy 300
Class 91, number of noisy 300
Class 92, number of noisy 300
Class 93, number of noisy 300
Class 94, number of noisy 300
Class 95, number of noisy 300
Class 96, number of noisy 300
Class 97, number of noisy 300
Class 98, number of noisy 300
Class 99, number of noisy 300
30000
Print noisy label generation statistics:
Noisy class 0, has 523 samples.
Noisy class 1, has 482 samples.
Noisy class 2, has 489 samples.
Noisy class 3, has 504 samples.
Noisy class 4, has 507 samples.
Noisy class 5, has 519 samples.
Noisy class 6, has 486 samples.
Noisy class 7, has 518 samples.
Noisy class 8, has 495 samples.
Noisy class 9, has 505 samples.
Noisy class 10, has 507 samples.
Noisy class 11, has 472 samples.
Noisy class 12, has 491 samples.
Noisy class 13, has 480 samples.
Noisy class 14, has 525 samples.
Noisy class 15, has 484 samples.
Noisy class 16, has 508 samples.
Noisy class 17, has 487 samples.
Noisy class 18, has 505 samples.
Noisy class 19, has 533 samples.
Noisy class 20, has 542 samples.
Noisy class 21, has 496 samples.
Noisy class 22, has 539 samples.
Noisy class 23, has 531 samples.
Noisy class 24, has 463 samples.
Noisy class 25, has 498 samples.
Noisy class 26, has 509 samples.
Noisy class 27, has 504 samples.
Noisy class 28, has 515 samples.
Noisy class 29, has 527 samples.
Noisy class 30, has 488 samples.
Noisy class 31, has 495 samples.
Noisy class 32, has 474 samples.
Noisy class 33, has 495 samples.
Noisy class 34, has 490 samples.
Noisy class 35, has 508 samples.
Noisy class 36, has 516 samples.
Noisy class 37, has 475 samples.
Noisy class 38, has 488 samples.
Noisy class 39, has 512 samples.
Noisy class 40, has 519 samples.
Noisy class 41, has 488 samples.
Noisy class 42, has 490 samples.
Noisy class 43, has 499 samples.
Noisy class 44, has 513 samples.
Noisy class 45, has 493 samples.
Noisy class 46, has 490 samples.
Noisy class 47, has 492 samples.
Noisy class 48, has 492 samples.
Noisy class 49, has 490 samples.
Noisy class 50, has 508 samples.
Noisy class 51, has 487 samples.
Noisy class 52, has 500 samples.
Noisy class 53, has 506 samples.
Noisy class 54, has 474 samples.
Noisy class 55, has 496 samples.
Noisy class 56, has 494 samples.
Noisy class 57, has 496 samples.
Noisy class 58, has 468 samples.
Noisy class 59, has 490 samples.
Noisy class 60, has 491 samples.
Noisy class 61, has 495 samples.
Noisy class 62, has 501 samples.
Noisy class 63, has 533 samples.
Noisy class 64, has 502 samples.
Noisy class 65, has 476 samples.
Noisy class 66, has 482 samples.
Noisy class 67, has 486 samples.
Noisy class 68, has 498 samples.
Noisy class 69, has 514 samples.
Noisy class 70, has 501 samples.
Noisy class 71, has 487 samples.
Noisy class 72, has 479 samples.
Noisy class 73, has 502 samples.
Noisy class 74, has 479 samples.
Noisy class 75, has 507 samples.
Noisy class 76, has 498 samples.
Noisy class 77, has 496 samples.
Noisy class 78, has 510 samples.
Noisy class 79, has 495 samples.
Noisy class 80, has 508 samples.
Noisy class 81, has 499 samples.
Noisy class 82, has 521 samples.
Noisy class 83, has 513 samples.
Noisy class 84, has 484 samples.
Noisy class 85, has 492 samples.
Noisy class 86, has 480 samples.
Noisy class 87, has 486 samples.
Noisy class 88, has 501 samples.
Noisy class 89, has 499 samples.
Noisy class 90, has 477 samples.
Noisy class 91, has 507 samples.
Noisy class 92, has 507 samples.
Noisy class 93, has 514 samples.
Noisy class 94, has 507 samples.
Noisy class 95, has 509 samples.
Noisy class 96, has 495 samples.
Noisy class 97, has 529 samples.
Noisy class 98, has 529 samples.
Noisy class 99, has 541 samples.
Files already downloaded and verified
Num of train 50000
Num of test 10000
Iter 0: loss=151110.1651, test_acc=0.0396
Iter 1: loss=154083.9007, test_acc=0.0692
Iter 2: loss=157122.4436, test_acc=0.0812
Iter 3: loss=160223.0777, test_acc=0.0910
Iter 4: loss=163385.5506, test_acc=0.1232
Iter 5: loss=166611.6324, test_acc=0.1492
Iter 6: loss=169901.8942, test_acc=0.1801
Iter 7: loss=173258.6009, test_acc=0.1815
Iter 8: loss=176682.7311, test_acc=0.2052
Iter 9: loss=180174.9674, test_acc=0.2075
Iter 10: loss=183738.4715, test_acc=0.2269
Iter 11: loss=187372.8490, test_acc=0.2388
Iter 12: loss=191080.2158, test_acc=0.2453
Iter 13: loss=194862.0526, test_acc=0.2577
Iter 14: loss=198719.8059, test_acc=0.2921
Iter 15: loss=202654.7166, test_acc=0.2891
Iter 16: loss=206667.7463, test_acc=0.3092
Iter 17: loss=210762.4683, test_acc=0.3255
Iter 18: loss=214938.0186, test_acc=0.3340
Iter 19: loss=219197.8479, test_acc=0.3452
Iter 20: loss=223542.2631, test_acc=0.3470
Iter 21: loss=227975.2175, test_acc=0.3675
Iter 22: loss=232495.2305, test_acc=0.3661
Iter 23: loss=237107.3813, test_acc=0.3848
Iter 24: loss=241811.0433, test_acc=0.3969
Iter 25: loss=246608.8017, test_acc=0.3916
Iter 26: loss=251502.8743, test_acc=0.4215
Iter 27: loss=256494.7246, test_acc=0.4130
Iter 28: loss=261587.4648, test_acc=0.4179
Iter 29: loss=266781.0972, test_acc=0.4263
Iter 30: loss=272080.1508, test_acc=0.4310
Iter 31: loss=277484.5430, test_acc=0.4463
Iter 32: loss=282996.8878, test_acc=0.4390
Iter 33: loss=288619.5373, test_acc=0.4508
Iter 34: loss=294354.9988, test_acc=0.4550
Iter 35: loss=300205.7977, test_acc=0.4467
Iter 36: loss=306172.5729, test_acc=0.4622
Iter 37: loss=312260.3562, test_acc=0.4668
Iter 38: loss=318469.0605, test_acc=0.4529
Iter 39: loss=324801.2627, test_acc=0.4743
Iter 40: loss=331262.8734, test_acc=0.4718
Iter 41: loss=337850.9145, test_acc=0.4661
Iter 42: loss=344572.9515, test_acc=0.4659
Iter 43: loss=351426.8160, test_acc=0.4732
Iter 44: loss=358421.9992, test_acc=0.4606
Iter 45: loss=365555.5152, test_acc=0.4719
Iter 46: loss=372829.9723, test_acc=0.4812
Iter 47: loss=380250.8165, test_acc=0.4814
Iter 48: loss=387821.5490, test_acc=0.4719
Iter 49: loss=395542.0917, test_acc=0.4693
Iter 50: loss=403417.1763, test_acc=0.4709
Iter 51: loss=411453.3267, test_acc=0.4746
Iter 52: loss=419645.9366, test_acc=0.4737
Iter 53: loss=428004.0449, test_acc=0.4706
Iter 54: loss=436528.3002, test_acc=0.4727
Iter 55: loss=445226.6342, test_acc=0.4764
Iter 56: loss=454094.9794, test_acc=0.4756
Iter 57: loss=463142.9332, test_acc=0.4695
Iter 58: loss=472372.4202, test_acc=0.4493
Iter 59: loss=481783.5535, test_acc=0.4720
Iter 60: loss=491385.4447, test_acc=0.4561
Iter 61: loss=501180.2910, test_acc=0.4559
Iter 62: loss=511166.4689, test_acc=0.4677
Iter 63: loss=521356.8933, test_acc=0.4459
Iter 64: loss=531754.0820, test_acc=0.4532
Iter 65: loss=542353.7200, test_acc=0.4538
Iter 66: loss=553166.2919, test_acc=0.4565
Iter 67: loss=564194.4860, test_acc=0.4549
Iter 68: loss=575447.3236, test_acc=0.4484
Iter 69: loss=586920.0933, test_acc=0.4489
Iter 70: loss=598624.0137, test_acc=0.4492
Iter 71: loss=610562.6045, test_acc=0.4511
Iter 72: loss=622741.5367, test_acc=0.4408
Iter 73: loss=635163.5061, test_acc=0.4428
Iter 74: loss=647834.1322, test_acc=0.4500
Iter 75: loss=660757.5184, test_acc=0.4426
Iter 76: loss=673937.9565, test_acc=0.4497
Iter 77: loss=687385.3655, test_acc=0.4409
Iter 78: loss=701100.7319, test_acc=0.4422
Iter 79: loss=715088.6556, test_acc=0.4399
Iter 80: loss=729356.6140, test_acc=0.4378
Iter 81: loss=743911.9750, test_acc=0.4257
Iter 82: loss=758756.9993, test_acc=0.4245
Iter 83: loss=773898.8367, test_acc=0.4307
Iter 84: loss=789346.2312, test_acc=0.4434
Iter 85: loss=805102.2224, test_acc=0.4355
Iter 86: loss=821170.1970, test_acc=0.4264
Iter 87: loss=837561.4033, test_acc=0.4312
Iter 88: loss=854280.4558, test_acc=0.4373
Iter 89: loss=871334.3789, test_acc=0.4261
Iter 90: loss=888729.9602, test_acc=0.4354
Iter 91: loss=906472.4236, test_acc=0.4295
Iter 92: loss=924570.4648, test_acc=0.4286
Iter 93: loss=943028.0605, test_acc=0.4354
Iter 94: loss=961858.7175, test_acc=0.4353
Iter 95: loss=981064.7869, test_acc=0.4355
Iter 96: loss=1000655.1917, test_acc=0.4262
Iter 97: loss=1020637.0298, test_acc=0.4294
Iter 98: loss=1041020.3865, test_acc=0.4260
Iter 99: loss=1061809.5308, test_acc=0.4372
Iter 100: loss=1083014.9993, test_acc=0.4231
Iter 101: loss=1104644.7632, test_acc=0.4263
Iter 102: loss=1126707.5024, test_acc=0.4326
Iter 103: loss=1149212.1428, test_acc=0.4365
Iter 104: loss=1172166.9805, test_acc=0.4348
Iter 105: loss=1195580.2104, test_acc=0.4289
Iter 106: loss=1219458.6724, test_acc=0.4234
Iter 107: loss=1243820.5129, test_acc=0.4301
Iter 108: loss=1268665.6245, test_acc=0.4362
Iter 109: loss=1294009.1436, test_acc=0.4347
Iter 110: loss=1319861.3423, test_acc=0.4295
Iter 111: loss=1346229.5991, test_acc=0.4292
Iter 112: loss=1373123.7727, test_acc=0.4269
Iter 113: loss=1400556.5725, test_acc=0.4360
Iter 114: loss=1428536.7458, test_acc=0.4278
Iter 115: loss=1457080.2117, test_acc=0.4308
Iter 116: loss=1486193.4700, test_acc=0.4289
Iter 117: loss=1515887.5210, test_acc=0.4304
Iter 118: loss=1546176.3303, test_acc=0.4290
Iter 119: loss=1577069.3606, test_acc=0.4397
Iter 120: loss=1608583.5571, test_acc=0.4301
Iter 121: loss=1640726.8799, test_acc=0.4358
Iter 122: loss=1673512.5220, test_acc=0.4414
Iter 123: loss=1706955.2637, test_acc=0.4267
Iter 124: loss=1741065.9751, test_acc=0.4409
Iter 125: loss=1775856.2910, test_acc=0.4370
Iter 126: loss=1811346.2607, test_acc=0.4330
Iter 127: loss=1847545.5894, test_acc=0.4282
Iter 128: loss=1884468.9722, test_acc=0.4370
Iter 129: loss=1922128.6401, test_acc=0.4334
Iter 130: loss=1960541.9941, test_acc=0.4354
Iter 131: loss=1999726.0952, test_acc=0.4372
Iter 132: loss=2039693.1880, test_acc=0.4291
Iter 133: loss=2080457.5283, test_acc=0.4311
Iter 134: loss=2122038.7734, test_acc=0.4354
Iter 135: loss=2164452.6543, test_acc=0.4420
Iter 136: loss=2207713.0254, test_acc=0.4350
Iter 137: loss=2251838.6182, test_acc=0.4382
Iter 138: loss=2296847.0566, test_acc=0.4381
Iter 139: loss=2342757.0933, test_acc=0.4383
Iter 140: loss=2389584.5024, test_acc=0.4345
Iter 141: loss=2437347.5103, test_acc=0.4389
Iter 142: loss=2486066.1821, test_acc=0.4398
Iter 143: loss=2535760.8027, test_acc=0.4361
Iter 144: loss=2586447.6343, test_acc=0.4382
Iter 145: loss=2638149.4136, test_acc=0.4349
Iter 146: loss=2690884.6118, test_acc=0.4330
Iter 147: loss=2744674.4146, test_acc=0.4335
Iter 148: loss=2799541.7241, test_acc=0.4386
Iter 149: loss=2855504.7227, test_acc=0.4323
Iter 150: loss=2912587.3311, test_acc=0.4372
Iter 151: loss=2970810.1177, test_acc=0.4427
Iter 152: loss=3030200.2876, test_acc=0.4371
Iter 153: loss=3090776.6641, test_acc=0.4410
Iter 154: loss=3152564.1113, test_acc=0.4421
Iter 155: loss=3215587.8516, test_acc=0.4445
Iter 156: loss=3279873.0566, test_acc=0.4493
Iter 157: loss=3345441.0654, test_acc=0.4485
Iter 158: loss=3412323.6191, test_acc=0.4406
Iter 159: loss=3480542.0586, test_acc=0.4370
Iter 160: loss=3550126.9561, test_acc=0.4429
Iter 161: loss=3621101.6377, test_acc=0.4471
Iter 162: loss=3693496.1865, test_acc=0.4437
Iter 163: loss=3767338.9131, test_acc=0.4474
Iter 164: loss=3842658.1260, test_acc=0.4454
Iter 165: loss=3919483.9443, test_acc=0.4442
Iter 166: loss=3997846.2930, test_acc=0.4475
Iter 167: loss=4077775.7666, test_acc=0.4449
Iter 168: loss=4159305.1230, test_acc=0.4436
Iter 169: loss=4242464.8467, test_acc=0.4427
Iter 170: loss=4327286.0498, test_acc=0.4411
Iter 171: loss=4413805.5205, test_acc=0.4438
Iter 172: loss=4502053.4805, test_acc=0.4437
Iter 173: loss=4592067.4629, test_acc=0.4447
Iter 174: loss=4683881.9531, test_acc=0.4449
Iter 175: loss=4777533.4307, test_acc=0.4439
Iter 176: loss=4873057.2910, test_acc=0.4456
Iter 177: loss=4970491.0498, test_acc=0.4505
Iter 178: loss=5069874.6758, test_acc=0.4480
Iter 179: loss=5171245.4971, test_acc=0.4522
Iter 180: loss=5274643.3428, test_acc=0.4511
Iter 181: loss=5380109.2188, test_acc=0.4496
Iter 182: loss=5487683.4248, test_acc=0.4519
Iter 183: loss=5597412.1748, test_acc=0.4520
Iter 184: loss=5709332.9326, test_acc=0.4527
Iter 185: loss=5823492.7881, test_acc=0.4537
Iter 186: loss=5939935.6543, test_acc=0.4530
Iter 187: loss=6058708.0391, test_acc=0.4490
Iter 188: loss=6179855.9297, test_acc=0.4524
Iter 189: loss=6303426.3301, test_acc=0.4506
Iter 190: loss=6429468.3926, test_acc=0.4505
Iter 191: loss=6558032.0391, test_acc=0.4501
Iter 192: loss=6689166.5391, test_acc=0.4523
Iter 193: loss=6822923.4023, test_acc=0.4498
Iter 194: loss=6959354.3887, test_acc=0.4514
Iter 195: loss=7098516.7461, test_acc=0.4539
Iter 196: loss=7240460.6348, test_acc=0.4504
Iter 197: loss=7385243.8477, test_acc=0.4546
Iter 198: loss=7532922.8945, test_acc=0.4504
Iter 199: loss=7683554.1133, test_acc=0.4520
>
The log of 0.3 asymmetric noise:

> We are using cuda
Namespace(batch_size=128, dataset='CIFAR100', gpus='0', grad_bound=5.0, noise_rate=0.3, noise_type='asymmetric', num_workers=10, root='../database/', seed=123)
Files already downloaded and verified
Actual noise 0.30
Files already downloaded and verified
Num of train 50000
Num of test 10000
Iter 0: loss=375046.7173, test_acc=0.0613
Iter 1: loss=382480.1832, test_acc=0.0961
Iter 2: loss=390074.7953, test_acc=0.1450
Iter 3: loss=397820.8396, test_acc=0.1721
Iter 4: loss=405719.8138, test_acc=0.2166
Iter 5: loss=413778.1838, test_acc=0.2552
Iter 6: loss=421998.9639, test_acc=0.2681
Iter 7: loss=430385.0475, test_acc=0.3153
Iter 8: loss=438942.1523, test_acc=0.3238
Iter 9: loss=447670.9154, test_acc=0.3669
Iter 10: loss=456576.8453, test_acc=0.3812
Iter 11: loss=465661.7429, test_acc=0.3777
Iter 12: loss=474928.8083, test_acc=0.4283
Iter 13: loss=484383.2272, test_acc=0.4557
Iter 14: loss=494029.1384, test_acc=0.4772
Iter 15: loss=503869.7151, test_acc=0.4849
Iter 16: loss=513905.1027, test_acc=0.5015
Iter 17: loss=524144.2594, test_acc=0.4953
Iter 18: loss=534589.4242, test_acc=0.5260
Iter 19: loss=545243.6962, test_acc=0.5194
Iter 20: loss=556112.2666, test_acc=0.5411
Iter 21: loss=567197.3544, test_acc=0.5319
Iter 22: loss=578504.9205, test_acc=0.5365
Iter 23: loss=590040.3607, test_acc=0.5601
Iter 24: loss=601807.1689, test_acc=0.5519
Iter 25: loss=613808.1895, test_acc=0.5631
Iter 26: loss=626051.7893, test_acc=0.5638
Iter 27: loss=638539.2802, test_acc=0.5789
Iter 28: loss=651273.9371, test_acc=0.5894
Iter 29: loss=664267.7961, test_acc=0.5797
Iter 30: loss=677521.5045, test_acc=0.5847
Iter 31: loss=691038.9636, test_acc=0.5680
Iter 32: loss=704828.5426, test_acc=0.5806
Iter 33: loss=718892.4802, test_acc=0.5899
Iter 34: loss=733237.5420, test_acc=0.5921
Iter 35: loss=747871.4181, test_acc=0.5961
Iter 36: loss=762797.5485, test_acc=0.5983
Iter 37: loss=778020.3584, test_acc=0.6006
Iter 38: loss=793547.3022, test_acc=0.6040
Iter 39: loss=809388.8743, test_acc=0.6098
Iter 40: loss=825546.9568, test_acc=0.5987
Iter 41: loss=842025.5754, test_acc=0.6086
Iter 42: loss=858834.7166, test_acc=0.5950
Iter 43: loss=875984.3521, test_acc=0.6141
Iter 44: loss=893470.8193, test_acc=0.6001
Iter 45: loss=911312.4114, test_acc=0.5905
Iter 46: loss=929507.8982, test_acc=0.5946
Iter 47: loss=948066.1389, test_acc=0.6067
Iter 48: loss=966998.5000, test_acc=0.6113
Iter 49: loss=986307.9663, test_acc=0.6030
Iter 50: loss=1006005.4885, test_acc=0.6052
Iter 51: loss=1026093.8838, test_acc=0.6043
Iter 52: loss=1046586.6475, test_acc=0.5930
Iter 53: loss=1067489.3867, test_acc=0.6099
Iter 54: loss=1088809.8911, test_acc=0.6031
Iter 55: loss=1110555.3777, test_acc=0.6006
Iter 56: loss=1132740.1021, test_acc=0.6022
Iter 57: loss=1155365.3210, test_acc=0.6023
Iter 58: loss=1178441.4219, test_acc=0.6027
Iter 59: loss=1201982.2561, test_acc=0.5942
Iter 60: loss=1225990.8000, test_acc=0.6042
Iter 61: loss=1250482.2134, test_acc=0.5921
Iter 62: loss=1275463.6753, test_acc=0.6015
Iter 63: loss=1300942.2554, test_acc=0.5853
Iter 64: loss=1326934.7327, test_acc=0.5888
Iter 65: loss=1353442.5735, test_acc=0.5863
Iter 66: loss=1380485.9390, test_acc=0.5851
Iter 67: loss=1408065.6379, test_acc=0.5829
Iter 68: loss=1436198.3093, test_acc=0.5918
Iter 69: loss=1464894.7593, test_acc=0.5845
Iter 70: loss=1494162.1963, test_acc=0.5805
Iter 71: loss=1524017.5266, test_acc=0.5685
Iter 72: loss=1554470.5500, test_acc=0.5868
Iter 73: loss=1585531.3518, test_acc=0.5788
Iter 74: loss=1617210.8350, test_acc=0.5911
Iter 75: loss=1649529.4785, test_acc=0.5836
Iter 76: loss=1682490.7559, test_acc=0.5892
Iter 77: loss=1716111.7588, test_acc=0.5792
Iter 78: loss=1750409.7061, test_acc=0.5672
Iter 79: loss=1785387.3530, test_acc=0.5682
Iter 80: loss=1821068.4927, test_acc=0.5733
Iter 81: loss=1857461.9668, test_acc=0.5750
Iter 82: loss=1894583.6284, test_acc=0.5662
Iter 83: loss=1932448.8447, test_acc=0.5754
Iter 84: loss=1971069.0254, test_acc=0.5680
Iter 85: loss=2010464.3540, test_acc=0.5725
Iter 86: loss=2050645.2886, test_acc=0.5544
Iter 87: loss=2091635.3481, test_acc=0.5620
Iter 88: loss=2133437.9419, test_acc=0.5667
Iter 89: loss=2176079.9536, test_acc=0.5656
Iter 90: loss=2219579.5605, test_acc=0.5707
Iter 91: loss=2263940.0854, test_acc=0.5776
Iter 92: loss=2309189.3188, test_acc=0.5725
Iter 93: loss=2355344.1675, test_acc=0.5665
Iter 94: loss=2402425.3921, test_acc=0.5644
Iter 95: loss=2450449.4346, test_acc=0.5516
Iter 96: loss=2499430.2651, test_acc=0.5603
Iter 97: loss=2549393.6191, test_acc=0.5745
Iter 98: loss=2600362.2251, test_acc=0.5718
Iter 99: loss=2652339.2588, test_acc=0.5626
Iter 100: loss=2705358.2710, test_acc=0.5502
Iter 101: loss=2759438.2651, test_acc=0.5537
Iter 102: loss=2814601.6230, test_acc=0.5553
Iter 103: loss=2870865.1650, test_acc=0.5550
Iter 104: loss=2928259.3174, test_acc=0.5651
Iter 105: loss=2986803.7510, test_acc=0.5612
Iter 106: loss=3046508.2734, test_acc=0.5677
Iter 107: loss=3107413.4795, test_acc=0.5569
Iter 108: loss=3169537.3906, test_acc=0.5809
Iter 109: loss=3232902.5498, test_acc=0.5474
Iter 110: loss=3297535.5078, test_acc=0.5638
Iter 111: loss=3363462.1982, test_acc=0.5573
Iter 112: loss=3430709.2002, test_acc=0.5534
Iter 113: loss=3499299.8096, test_acc=0.5496
Iter 114: loss=3569257.0303, test_acc=0.5558
Iter 115: loss=3640622.5586, test_acc=0.5518
Iter 116: loss=3713404.2285, test_acc=0.5485
Iter 117: loss=3787645.9004, test_acc=0.5625
Iter 118: loss=3863376.0547, test_acc=0.5427
Iter 119: loss=3940620.0938, test_acc=0.5545
Iter 120: loss=4019405.7852, test_acc=0.5328
Iter 121: loss=4099771.5449, test_acc=0.5554
Iter 122: loss=4181741.5713, test_acc=0.5397
Iter 123: loss=4265356.6123, test_acc=0.5480
Iter 124: loss=4350640.5732, test_acc=0.5466
Iter 125: loss=4437627.4463, test_acc=0.5484
Iter 126: loss=4526359.4326, test_acc=0.5439
Iter 127: loss=4616851.1406, test_acc=0.5391
Iter 128: loss=4709173.6064, test_acc=0.5572
Iter 129: loss=4803339.7627, test_acc=0.5359
Iter 130: loss=4899385.2207, test_acc=0.5347
Iter 131: loss=4997342.7305, test_acc=0.5240
Iter 132: loss=5097258.5029, test_acc=0.5387
Iter 133: loss=5199189.1816, test_acc=0.5320
Iter 134: loss=5303144.0645, test_acc=0.5358
Iter 135: loss=5409175.6641, test_acc=0.5492
Iter 136: loss=5517340.2910, test_acc=0.5257
Iter 137: loss=5627663.4023, test_acc=0.5174
Iter 138: loss=5740201.4668, test_acc=0.5280
Iter 139: loss=5854981.7227, test_acc=0.5647
Iter 140: loss=5972042.9043, test_acc=0.5271
Iter 141: loss=6091460.1963, test_acc=0.5582
Iter 142: loss=6213272.1650, test_acc=0.5172
Iter 143: loss=6337517.1758, test_acc=0.5042
Iter 144: loss=6464251.4629, test_acc=0.5216
Iter 145: loss=6593489.5684, test_acc=0.5360
Iter 146: loss=6725340.9941, test_acc=0.5357
Iter 147: loss=6859815.5332, test_acc=0.5356
Iter 148: loss=6996983.2559, test_acc=0.5310
Iter 149: loss=7136905.2168, test_acc=0.5126
Iter 150: loss=7279610.4023, test_acc=0.5258
Iter 151: loss=7425159.8105, test_acc=0.5353
Iter 152: loss=7573626.6484, test_acc=0.5426
Iter 153: loss=7725076.9512, test_acc=0.5414
Iter 154: loss=7879555.3203, test_acc=0.5246
Iter 155: loss=8037115.6582, test_acc=0.5393
Iter 156: loss=8197827.1855, test_acc=0.5363
Iter 157: loss=8361756.1602, test_acc=0.5431
Iter 158: loss=8528953.1191, test_acc=0.5415
Iter 159: loss=8699505.6445, test_acc=0.5406
Iter 160: loss=8873466.4883, test_acc=0.5511
Iter 161: loss=9050893.4727, test_acc=0.5506
Iter 162: loss=9231882.1953, test_acc=0.5439
Iter 163: loss=9416489.5742, test_acc=0.5511
Iter 164: loss=9604789.0469, test_acc=0.5489
Iter 165: loss=9796847.5879, test_acc=0.5617
Iter 166: loss=9992757.2520, test_acc=0.5541
Iter 167: loss=10192581.9648, test_acc=0.5605
Iter 168: loss=10396405.4961, test_acc=0.5503
Iter 169: loss=10604301.4707, test_acc=0.5607
Iter 170: loss=10816345.1426, test_acc=0.5752
Iter 171: loss=11032637.9922, test_acc=0.5819
Iter 172: loss=11253254.9668, test_acc=0.5836
Iter 173: loss=11478289.8340, test_acc=0.5761
Iter 174: loss=11707823.6641, test_acc=0.5811
Iter 175: loss=11941947.5645, test_acc=0.5815
Iter 176: loss=12180755.0723, test_acc=0.5844
Iter 177: loss=12424341.1035, test_acc=0.5767
Iter 178: loss=12672799.9551, test_acc=0.5893
Iter 179: loss=12926223.8477, test_acc=0.5968
Iter 180: loss=13184714.9258, test_acc=0.5919
Iter 181: loss=13448373.3906, test_acc=0.5961
Iter 182: loss=13717314.7422, test_acc=0.5858
Iter 183: loss=13991630.0430, test_acc=0.5923
Iter 184: loss=14271436.0273, test_acc=0.5949
Iter 185: loss=14556831.2344, test_acc=0.5949
Iter 186: loss=14847939.0117, test_acc=0.5995
Iter 187: loss=15144872.6953, test_acc=0.5988
Iter 188: loss=15447737.3789, test_acc=0.6014
Iter 189: loss=15756663.0234, test_acc=0.6053
Iter 190: loss=16071764.5078, test_acc=0.6008
Iter 191: loss=16393170.3594, test_acc=0.6028
Iter 192: loss=16721007.6484, test_acc=0.6079
Iter 193: loss=17055402.3203, test_acc=0.6062
Iter 194: loss=17396480.6172, test_acc=0.6077
Iter 195: loss=17744380.3711, test_acc=0.6068
Iter 196: loss=18099242.8711, test_acc=0.6066
Iter 197: loss=18461200.1719, test_acc=0.6091
Iter 198: loss=18830397.0156, test_acc=0.6065
Iter 199: loss=19206980.9570, test_acc=0.6069
